[package]
name = "fjt"
version = "0.1.0"
authors = ["Kazuya Iimuro <ikazuya0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.3"
cortex-m-rt = "0.6.12"
panic_rtt = "0.2.0"

[dependencies.components]
git = "https://github.com/ikazuya0201/mouse_components.git"
branch = "develop/v0.2"
