[package]
name = "fjt"
version = "0.1.0"
authors = ["Kazuya Iimuro <ikazuya0201@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cortex-m = "0.6.3"
cortex-m-rt = "0.6.12"
panic_rtt = "0.2.0"
nb = "1.0.0"
jlink_rtt = "0.1.0"
heapless = "0.5.3"
libm = "0.2.1"
typenum = "1.12.0"
generic-array = "0.13.2"

[dependencies.once_cell]
version = "1.4.0"
default-features = false

[dependencies.lazy_static]
version = "1.4.0"
features = ["spin_no_std"]

[dependencies.stm32f4xx-hal]
version = "0.8.3"
features = ["stm32f413"]

[dependencies.components]
git = "https://github.com/ikazuya0201/mouse_components.git"
branch = "develop/v0.2"
features = ["debug"]

[dependencies.quantities]
git = "https://github.com/ikazuya0201/quantities.git"

[dependencies.embedded-hal]
version = "0.2.3"
features = ["unproven"]
